import type { StarterLanguage } from "../types";

export type TemplateFile = { path: string; content: string };

export type StarterTemplateBundle = {
  files: TemplateFile[];
  openPath: string;
};

export type StarterLanguageMeta = {
  id: StarterLanguage;
  title: string;
  subtitle: string;
  description: string;
  frontendStyle: string;
  highlights: string[];
};

export const STARTER_LANGUAGE_META: StarterLanguageMeta[] = [
  {
    id: "haskell",
    title: "Haskell / Plutus",
    subtitle: "Typed Cardano smart contracts",
    description:
      "Best for users who want a structured Plutus starter with your current compile pipeline still working.",
    frontendStyle: "Professional analytics dashboard",
    highlights: ["onchain + tests", "offchain TS helpers", "React frontend + tests"],
  },
  {
    id: "aiken",
    title: "Aiken",
    subtitle: "Modern Cardano smart contract language",
    description:
      "Great for cleaner Cardano contract authoring with simple project structure and frontend starter files.",
    frontendStyle: "Modern product-style landing + app shell",
    highlights: ["validator starter", "Aiken tests", "frontend + offchain starter"],
  },
  {
    id: "opshin",
    title: "Opshin",
    subtitle: "Python-based Cardano contracts",
    description:
      "Useful when you want Python-flavoured smart contract authoring plus pytest-ready starter structure.",
    frontendStyle: "Clean Python dApp console UI",
    highlights: ["Python onchain starter", "pytest structure", "frontend + offchain starter"],
  },
  {
    id: "helios",
    title: "Helios",
    subtitle: "JavaScript-friendly Cardano scripting",
    description:
      "A lightweight Cardano scripting starter with browser-friendly integration structure.",
    frontendStyle: "Minimal polished dApp interface",
    highlights: ["Helios contract starter", "JS tests", "frontend + offchain starter"],
  },
  {
    id: "midnight",
    title: "Midnight / Compact",
    subtitle: "Privacy-focused smart contract starter",
    description:
      "A clean starter for Compact-style Midnight development with structured onchain, offchain, frontend, and tests.",
    frontendStyle: "Premium privacy app dashboard",
    highlights: ["Compact contract starter", "onchain tests", "frontend + offchain starter"],
  },
];

function reactFrontendApp(language: StarterLanguage, title: string, accent: string) {
  return `import React from "react";

const accent = "${accent}";
const stack = "${title}";

export default function App() {
  return (
    <div
      style={{
        minHeight: "100vh",
        background: "linear-gradient(135deg, #0f172a 0%, #111827 45%, #1e293b 100%)",
        color: "#e5e7eb",
        fontFamily: "Inter, system-ui, sans-serif",
        padding: "32px",
      }}
    >
      <div
        style={{
          maxWidth: 1120,
          margin: "0 auto",
          display: "grid",
          gap: 24,
        }}
      >
        <div
          style={{
            padding: 28,
            borderRadius: 24,
            background: "rgba(255,255,255,0.04)",
            border: "1px solid rgba(255,255,255,0.08)",
            boxShadow: "0 20px 50px rgba(0,0,0,0.25)",
          }}
        >
          <div
            style={{
              display: "inline-flex",
              padding: "6px 12px",
              borderRadius: 999,
              background: accent,
              color: "#0b1020",
              fontWeight: 800,
              fontSize: 12,
              marginBottom: 16,
            }}
          >
            ${language.toUpperCase()} STARTER
          </div>

          <h1 style={{ fontSize: 40, margin: "0 0 12px", lineHeight: 1.1 }}>
            ${title} Full-Stack Starter
          </h1>

          <p style={{ margin: 0, maxWidth: 760, color: "#cbd5e1", fontSize: 16 }}>
            This frontend is generated by the IDE starter system. Connect your wallet, call your offchain helpers,
            and wire contract interactions here.
          </p>
        </div>

        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
            gap: 20,
          }}
        >
          {[
            { title: "Wallet", body: "Connect wallet and display address / balance." },
            { title: "Offchain API", body: "Call transaction builders and encode parameters." },
            { title: "Contract Actions", body: "Expose deploy, lock, unlock, mint, burn or custom actions." },
            { title: "Tests", body: "Use frontend unit tests to validate render and state changes." },
          ].map((item) => (
            <div
              key={item.title}
              style={{
                borderRadius: 22,
                padding: 20,
                background: "rgba(255,255,255,0.04)",
                border: "1px solid rgba(255,255,255,0.08)",
              }}
            >
              <h3 style={{ marginTop: 0, marginBottom: 10 }}>{item.title}</h3>
              <p style={{ margin: 0, color: "#cbd5e1" }}>{item.body}</p>
            </div>
          ))}
        </div>

        <div
          style={{
            display: "flex",
            gap: 12,
            flexWrap: "wrap",
          }}
        >
          <button
            style={{
              padding: "12px 18px",
              borderRadius: 14,
              border: "none",
              cursor: "pointer",
              fontWeight: 700,
              background: accent,
              color: "#0b1020",
            }}
          >
            Connect Wallet
          </button>

          <button
            style={{
              padding: "12px 18px",
              borderRadius: 14,
              border: "1px solid rgba(255,255,255,0.12)",
              cursor: "pointer",
              fontWeight: 700,
              background: "transparent",
              color: "#e5e7eb",
            }}
          >
            Open Contract Panel
          </button>
        </div>
      </div>
    </div>
  );
}
`;
}

function reactFrontendTest() {
  return `import { describe, it, expect } from "vitest";
import { render, screen } from "@testing-library/react";
import App from "../src/App";

describe("frontend App", () => {
  it("renders starter heading", () => {
    render(<App />);
    expect(screen.getByText(/Full-Stack Starter/i)).toBeTruthy();
  });
});
`;
}

function frontendPackageJson() {
  return `{
  "name": "cardano-starter-frontend",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "test": "vitest"
  },
  "dependencies": {
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
  "devDependencies": {
    "@testing-library/react": "^16.0.1",
    "@types/react": "^18.3.5",
    "@types/react-dom": "^18.3.0",
    "typescript": "^5.6.2",
    "vite": "^5.4.8",
    "vitest": "^2.1.1"
  }
}
`;
}

function offchainPackageJson(name: string) {
  return `{
  "name": "${name}-offchain",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "scripts": {
    "test": "node --test"
  }
}
`;
}

function offchainIndexTs(language: StarterLanguage) {
  return `export type ContractAction =
  | "lock"
  | "unlock"
  | "mint"
  | "burn"
  | "custom";

export type BuildTxInput = {
  action: ContractAction;
  walletAddress: string;
  amountLovelace?: number;
  metadata?: Record<string, unknown>;
};

export function build${capitalize(language)}TxPayload(input: BuildTxInput) {
  if (!input.walletAddress) {
    throw new Error("walletAddress is required");
  }

  return {
    stack: "${language}",
    action: input.action,
    walletAddress: input.walletAddress,
    amountLovelace: input.amountLovelace ?? 0,
    metadata: input.metadata ?? {},
  };
}
`;
}

function offchainTestTs(language: StarterLanguage) {
  return `import test from "node:test";
import assert from "node:assert/strict";
import { build${capitalize(language)}TxPayload } from "../src/index";

test("build${capitalize(language)}TxPayload builds a payload", () => {
  const payload = build${capitalize(language)}TxPayload({
    action: "lock",
    walletAddress: "addr_test1...",
    amountLovelace: 5000000,
  });

  assert.equal(payload.stack, "${language}");
  assert.equal(payload.action, "lock");
  assert.equal(payload.amountLovelace, 5000000);
});
`;
}

function readme(languageTitle: string, folder: string) {
  return `# ${folder}

This starter was generated from the IDE language setup page.

## Included structure

- onchain
- onchain tests
- offchain
- offchain tests
- frontend
- frontend tests

## Notes

- Haskell starter is aligned with your current backend compile flow.
- Aiken, Opshin, Helios, and Midnight starters are scaffolded cleanly, but compile wiring is not yet connected in the current backend.
`;
}

function buildHaskellStarter(folder: string): StarterTemplateBundle {
  return {
    openPath: `${folder}/onchain/src/Contract.hs`,
    files: [
      {
        path: `${folder}/README.md`,
        content: readme("Haskell / Plutus", folder),
      },
      {
        path: `${folder}/onchain/cabal.project`,
        content: `packages: .
`,
      },
      {
        path: `${folder}/onchain/${folder}-onchain.cabal`,
        content: `cabal-version:      3.0
name:               ${folder}-onchain
version:            0.1.0.0
build-type:         Simple

common shared
  default-language: GHC2021
  ghc-options:      -Wall
  hs-source-dirs:   src
  build-depends:
      base >=4.14 && <5

library
  import:           shared
  exposed-modules:  Contract

executable export-validator
  default-language: GHC2021
  main-is:          export-validator.hs
  hs-source-dirs:   app, src
  build-depends:
      base >=4.14 && <5,
      ${folder}-onchain

executable export-policy
  default-language: GHC2021
  main-is:          export-policy.hs
  hs-source-dirs:   app, src
  build-depends:
      base >=4.14 && <5,
      ${folder}-onchain

test-suite onchain-tests
  default-language: GHC2021
  type:             exitcode-stdio-1.0
  main-is:          Spec.hs
  hs-source-dirs:   test, src
  build-depends:
      base >=4.14 && <5,
      ${folder}-onchain
`,
      },
      {
        path: `${folder}/onchain/src/Contract.hs`,
        content: `module Contract where

validatorName :: String
validatorName = "Starter Haskell Validator"

validatorCborHex :: String
validatorCborHex = "4e4d01000033222220051200120011"

policyName :: String
policyName = "Starter Haskell Minting Policy"

policyCborHex :: String
policyCborHex = "4e4d01000033222220051200120022"
`,
      },
      {
        path: `${folder}/onchain/app/export-validator.hs`,
        content: `module Main where

import System.Directory (createDirectoryIfMissing)
import System.FilePath ((</>))
import Contract

main :: IO ()
main = do
  createDirectoryIfMissing True "artifacts"
  writeFile ("artifacts" </> "validator.plutus") validatorName
  writeFile ("artifacts" </> "validator.cbor") validatorCborHex
  writeFile ("artifacts" </> "validator.script") validatorCborHex
  putStrLn "validator artifacts written"
`,
      },
      {
        path: `${folder}/onchain/app/export-policy.hs`,
        content: `module Main where

import System.Directory (createDirectoryIfMissing)
import System.FilePath ((</>))
import Contract

main :: IO ()
main = do
  createDirectoryIfMissing True "artifacts"
  writeFile ("artifacts" </> "policy.plutus") policyName
  writeFile ("artifacts" </> "policy.cbor") policyCborHex
  writeFile ("artifacts" </> "policy.script") policyCborHex
  putStrLn "policy artifacts written"
`,
      },
      {
        path: `${folder}/onchain/test/Spec.hs`,
        content: `module Main where

import Contract
import System.Exit (exitFailure)

assert :: Bool -> String -> IO ()
assert condition message =
  if condition then pure () else putStrLn message >> exitFailure

main :: IO ()
main = do
  assert (not (null validatorName)) "validatorName should not be empty"
  assert (not (null validatorCborHex)) "validatorCborHex should not be empty"
  assert (not (null policyName)) "policyName should not be empty"
  assert (not (null policyCborHex)) "policyCborHex should not be empty"
  putStrLn "onchain tests passed"
`,
      },
      {
        path: `${folder}/offchain/package.json`,
        content: offchainPackageJson(folder),
      },
      {
        path: `${folder}/offchain/src/index.ts`,
        content: offchainIndexTs("haskell"),
      },
      {
        path: `${folder}/offchain/tests/index.test.ts`,
        content: offchainTestTs("haskell"),
      },
      {
        path: `${folder}/frontend/package.json`,
        content: frontendPackageJson(),
      },
      {
        path: `${folder}/frontend/src/App.tsx`,
        content: reactFrontendApp("haskell", "Haskell / Plutus", "#38bdf8"),
      },
      {
        path: `${folder}/frontend/tests/App.test.tsx`,
        content: reactFrontendTest(),
      },
      {
        path: `${folder}/artifacts/.gitkeep`,
        content: ``,
      },
    ],
  };
}

function buildAikenStarter(folder: string): StarterTemplateBundle {
  return {
    openPath: `${folder}/onchain/validators/main.ak`,
    files: [
      {
        path: `${folder}/README.md`,
        content: readme("Aiken", folder),
      },
      {
        path: `${folder}/onchain/aiken.toml`,
        content: `name = "${folder}"
version = "0.1.0"
license = "Apache-2.0"
description = "Aiken full-stack starter"
`,
      },
      {
        path: `${folder}/onchain/validators/main.ak`,
        content: `validator starter_spend {
  spend(datum, redeemer, ctx) {
    True
  }
}
`,
      },
      {
        path: `${folder}/onchain/tests/starter_test.ak`,
        content: `test starter_contract_smoke_test() {
  True?
}
`,
      },
      {
        path: `${folder}/offchain/package.json`,
        content: offchainPackageJson(folder),
      },
      {
        path: `${folder}/offchain/src/index.ts`,
        content: offchainIndexTs("aiken"),
      },
      {
        path: `${folder}/offchain/tests/index.test.ts`,
        content: offchainTestTs("aiken"),
      },
      {
        path: `${folder}/frontend/package.json`,
        content: frontendPackageJson(),
      },
      {
        path: `${folder}/frontend/src/App.tsx`,
        content: reactFrontendApp("aiken", "Aiken", "#a78bfa"),
      },
      {
        path: `${folder}/frontend/tests/App.test.tsx`,
        content: reactFrontendTest(),
      },
      {
        path: `${folder}/artifacts/.gitkeep`,
        content: ``,
      },
    ],
  };
}

function buildOpshinStarter(folder: string): StarterTemplateBundle {
  return {
    openPath: `${folder}/onchain/contracts/main.py`,
    files: [
      {
        path: `${folder}/README.md`,
        content: readme("Opshin", folder),
      },
      {
        path: `${folder}/onchain/contracts/main.py`,
        content: `from typing import Any

def validator(datum: Any, redeemer: Any, context: Any) -> bool:
    return True
`,
      },
      {
        path: `${folder}/onchain/tests/test_main.py`,
        content: `from contracts.main import validator

def test_validator_returns_true():
    assert validator(None, None, None) is True
`,
      },
      {
        path: `${folder}/offchain/package.json`,
        content: offchainPackageJson(folder),
      },
      {
        path: `${folder}/offchain/src/index.ts`,
        content: offchainIndexTs("opshin"),
      },
      {
        path: `${folder}/offchain/tests/index.test.ts`,
        content: offchainTestTs("opshin"),
      },
      {
        path: `${folder}/frontend/package.json`,
        content: frontendPackageJson(),
      },
      {
        path: `${folder}/frontend/src/App.tsx`,
        content: reactFrontendApp("opshin", "Opshin", "#34d399"),
      },
      {
        path: `${folder}/frontend/tests/App.test.tsx`,
        content: reactFrontendTest(),
      },
      {
        path: `${folder}/artifacts/.gitkeep`,
        content: ``,
      },
    ],
  };
}

function buildHeliosStarter(folder: string): StarterTemplateBundle {
  return {
    openPath: `${folder}/onchain/contracts/main.hl`,
    files: [
      {
        path: `${folder}/README.md`,
        content: readme("Helios", folder),
      },
      {
        path: `${folder}/onchain/contracts/main.hl`,
        content: `spending starter

func main(_, _, _) -> Bool {
  true
}
`,
      },
      {
        path: `${folder}/onchain/tests/main.test.js`,
        content: `import test from "node:test";
import assert from "node:assert/strict";

test("helios smoke test placeholder", () => {
  assert.equal(true, true);
});
`,
      },
      {
        path: `${folder}/offchain/package.json`,
        content: offchainPackageJson(folder),
      },
      {
        path: `${folder}/offchain/src/index.ts`,
        content: offchainIndexTs("helios"),
      },
      {
        path: `${folder}/offchain/tests/index.test.ts`,
        content: offchainTestTs("helios"),
      },
      {
        path: `${folder}/frontend/package.json`,
        content: frontendPackageJson(),
      },
      {
        path: `${folder}/frontend/src/App.tsx`,
        content: reactFrontendApp("helios", "Helios", "#f59e0b"),
      },
      {
        path: `${folder}/frontend/tests/App.test.tsx`,
        content: reactFrontendTest(),
      },
      {
        path: `${folder}/artifacts/.gitkeep`,
        content: ``,
      },
    ],
  };
}

function buildMidnightStarter(folder: string): StarterTemplateBundle {
  return {
    openPath: `${folder}/onchain/contracts/main.compact`,
    files: [
      {
        path: `${folder}/README.md`,
        content: readme("Midnight / Compact", folder),
      },
      {
        path: `${folder}/onchain/contracts/main.compact`,
        content: `// Midnight Compact starter
// Replace this placeholder with your Compact contract.

export circuit main(): [] {
  return [];
}
`,
      },
      {
        path: `${folder}/onchain/tests/main.test.ts`,
        content: `import test from "node:test";
import assert from "node:assert/strict";

test("midnight starter smoke test", () => {
  assert.equal(true, true);
});
`,
      },
      {
        path: `${folder}/offchain/package.json`,
        content: offchainPackageJson(folder),
      },
      {
        path: `${folder}/offchain/src/index.ts`,
        content: offchainIndexTs("midnight"),
      },
      {
        path: `${folder}/offchain/tests/index.test.ts`,
        content: offchainTestTs("midnight"),
      },
      {
        path: `${folder}/frontend/package.json`,
        content: frontendPackageJson(),
      },
      {
        path: `${folder}/frontend/src/App.tsx`,
        content: reactFrontendApp("midnight", "Midnight / Compact", "#fb7185"),
      },
      {
        path: `${folder}/frontend/tests/App.test.tsx`,
        content: reactFrontendTest(),
      },
      {
        path: `${folder}/artifacts/.gitkeep`,
        content: ``,
      },
    ],
  };
}

export function buildLanguageStarterTemplate(language: StarterLanguage, folder: string): StarterTemplateBundle {
  switch (language) {
    case "haskell":
      return buildHaskellStarter(folder);
    case "aiken":
      return buildAikenStarter(folder);
    case "opshin":
      return buildOpshinStarter(folder);
    case "helios":
      return buildHeliosStarter(folder);
    case "midnight":
      return buildMidnightStarter(folder);
    default:
      return buildHaskellStarter(folder);
  }
}

function capitalize(value: string) {
  return value.charAt(0).toUpperCase() + value.slice(1);
}