import React from "react";

const accent = "#fb7185";
const stack = "Midnight / Compact";

export default function App() {
  return (
    <div
      style={{
        minHeight: "100vh",
        background: "linear-gradient(135deg, #0f172a 0%, #111827 45%, #1e293b 100%)",
        color: "#e5e7eb",
        fontFamily: "Inter, system-ui, sans-serif",
        padding: "32px",
      }}
    >
      <div
        style={{
          maxWidth: 1120,
          margin: "0 auto",
          display: "grid",
          gap: 24,
        }}
      >
        <div
          style={{
            padding: 28,
            borderRadius: 24,
            background: "rgba(255,255,255,0.04)",
            border: "1px solid rgba(255,255,255,0.08)",
            boxShadow: "0 20px 50px rgba(0,0,0,0.25)",
          }}
        >
          <div
            style={{
              display: "inline-flex",
              padding: "6px 12px",
              borderRadius: 999,
              background: accent,
              color: "#0b1020",
              fontWeight: 800,
              fontSize: 12,
              marginBottom: 16,
            }}
          >
            MIDNIGHT STARTER
          </div>

          <h1 style={{ fontSize: 40, margin: "0 0 12px", lineHeight: 1.1 }}>
            Midnight / Compact Full-Stack Starter
          </h1>

          <p style={{ margin: 0, maxWidth: 760, color: "#cbd5e1", fontSize: 16 }}>
            This frontend is generated by the IDE starter system. Connect your wallet, call your offchain helpers,
            and wire contract interactions here.
          </p>
        </div>

        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
            gap: 20,
          }}
        >
          {[
            { title: "Wallet", body: "Connect wallet and display address / balance." },
            { title: "Offchain API", body: "Call transaction builders and encode parameters." },
            { title: "Contract Actions", body: "Expose deploy, lock, unlock, mint, burn or custom actions." },
            { title: "Tests", body: "Use frontend unit tests to validate render and state changes." },
          ].map((item) => (
            <div
              key={item.title}
              style={{
                borderRadius: 22,
                padding: 20,
                background: "rgba(255,255,255,0.04)",
                border: "1px solid rgba(255,255,255,0.08)",
              }}
            >
              <h3 style={{ marginTop: 0, marginBottom: 10 }}>{item.title}</h3>
              <p style={{ margin: 0, color: "#cbd5e1" }}>{item.body}</p>
            </div>
          ))}
        </div>

        <div
          style={{
            display: "flex",
            gap: 12,
            flexWrap: "wrap",
          }}
        >
          <button
            style={{
              padding: "12px 18px",
              borderRadius: 14,
              border: "none",
              cursor: "pointer",
              fontWeight: 700,
              background: accent,
              color: "#0b1020",
            }}
          >
            Connect Wallet
          </button>

          <button
            style={{
              padding: "12px 18px",
              borderRadius: 14,
              border: "1px solid rgba(255,255,255,0.12)",
              cursor: "pointer",
              fontWeight: 700,
              background: "transparent",
              color: "#e5e7eb",
            }}
          >
            Open Contract Panel
          </button>
        </div>
      </div>
    </div>
  );
}
